### ISSUE TITLE
 flags are not displayed on the web

### ISSUE THREAD

**Issue by jpjf** [vanshg395/intl_phone_field#22]
When using the widget in the web environment, the flags are not seen, only the codes and in a very large size

**Comment by Grooviz** [comment]
@jpjf My guess is that you are using Windows which does not support flags emoji. 
Try to go here: https://emojipedia.org/flags/
And see if the flags are shown as emojis or just the 2 letters country code.

@vanshg395 maybe we should use icons instead of emojis to support all platforms? Or have a possible fallback to icons.
You may find icons (not under copyright protection) classified by ISO 2-letters code here: https://github.com/hjnilsson/country-flags.

Let me know if you want a PR for this.

**Comment by Grooviz** [comment]
Pull Request: https://github.com/vanshg395/intl_phone_field/pull/28

**Comment by vanshg395** [comment]
Merged #28, will update this
