### ISSUE TITLE
Add ability to change text style for flag button

### ISSUE THREAD

**Issue by ZaharL** [vanshg395/intl_phone_field#24]
I need to change the text style of the flag button. But there are no mechanisms to do this.

**Comment by marcaureln** [comment]
I know that it is been a very (very) long time that you had posted this issue, has we are willing to keep improving the package, can you provide more information about what you wanted to do, because the _flag button_ as you say, isn't actually a button, it's an Inkwell composed of the dropdown (Icon) + the flag itself (Image) + the country dial code (Text). The only items that you can style are the dropdown (with the new dropDownIcon parameter) and the country dial code (you cannot explicitly style it, but a global styling can, I though, do it).

**Comment by marcaureln** [comment]
Issue closed due to a lack of activity.
