### ISSUE TITLE
Doesn't reflect the Country Code on Firebase resulting in Invalid format!

### ISSUE THREAD

**Issue by adferaijaz** [vanshg395/intl_phone_field#60]
I was just using this package and this is what I did

IntlPhoneField(
                    style: TextStyle(fontSize: 16.0),
                    autofocus: true,
                    showDropdownIcon: false,
                    controller: phoneController,   // <= on passing this phoneController to Firebase, it only passes the phone number 
                    decoration: InputDecoration(
                      labelText: 'Phone Number',
                      border: UnderlineInputBorder(),
                    ),
                    initialCountryCode: 'IN',
                    onChanged: (phone) {
                      print(phone.completeNumber);
                    },
                    onCountryChanged: (phone) {
                      print('Country code changed to: ' + phone.countryCode);
                    },
                  ),

So am I doing anything wrong?

**Comment by marcaureln** [comment]
Sorry for my late answer, you don't get the country code because you can't access it from the controller (phoneController in your code), the controller is passed to the TextFormField composing the IntlPhoneField and this is why you only get the phone number (the user's input). To get the complete phone number, use the onChanged callback (the onCountryChanged callback also provide the complete phone number).
